### GET ALL NOTES
GET https://notes-backend-123230064-498485862524.asia-southeast2.run.app/notes

### CREATE NOTE
POST https://notes-backend-123230064-498485862524.asia-southeast2.run.app/notes
Content-Type: application/json

{
  "judul": "Catatan dari VSCode",
  "isi": "Ini isi catatan dari REST Client"
}

### UPDATE NOTE
PUT https://notes-backend-123230064-498485862524.asia-southeast2.run.app/notes/8
Content-Type: application/json

{
  "judul": "Update dari VSCode",
  "isi": "Isi sudah diubah"
}

### DELETE NOTE
DELETE https://notes-backend-123230064-498485862524.asia-southeast2.run.app/notes/1